### ISSUE TITLE
Need a 'catch' for errors

### ISSUE THREAD

**Issue by evantahler** [delighted/delighted-node#6]
The promise created when making an API call to send a survey `client.person.create(payload).then(...)` has no `catch()`.  If you send a payload which causes an API error (perhaps an invalid UTF8 char in the message payload), the API response never comes back... and the promise never resolves.  

A `catch()` should be added to the API promise, and it should have a timeout.

**Comment by evantahler** [comment]
Actually, it looks like none of the `Resource` API calls (which are extended by models like `person`) have a `catch` for the promise failure state: https://github.com/delighted/delighted-node/blob/master/lib/Resource.js

**Comment by kindjar** [comment]
In order to minimize our dependencies, we use an intentionally simple, but fully Promises/A+ compliant library (http://github.com/rse/thenable). As defined in the [Promises spec](https://promisesaplus.com/), you can pass a second handler to `then()` which is used if the promise is rejected. This is strictly equivalent to what `catch()` does in most libraries.

I did something like this recently:

```javascript
var response = client.person.create(payload)
.then(
  function(response) {
    console.log("response: ");
    console.log(response);
  }, 
  function(error) {
    console.log("ERROR");
    console.log(error);
  }
);
```

**Comment by evantahler** [comment]
Ah!

Thanks.  A note about this in the readme would be handy.

**Comment by kindjar** [comment]
I think you are right: we should probably add some more complete examples that show how to handle errors. Thanks for the feedback!

**Comment by mkdynamic** [comment]
+1 thanks @evantahler for reporting.

Updating the README sounds like a good move. Captured in an Issue: https://github.com/delighted/delighted-node/issues/8
